#!/bin/bash

clear

rm -f ../test_c/ans
touch ../test_c/ans
# for resetting ans if user removed solver

g++ -std=c++20 -fsanitize=address -o ../exec/main.e ../code/main.cpp
echo "main COMPILED"

g++ -std=c++20 -fsanitize=address -o ../exec/sol.e ../code/sol.cpp
echo "sol COMPILED"

g++ -std=c++20 -fsanitize=address -o ../exec/gen.e ../code/gen.cpp
echo "gen COMPILED"