#!/bin/bash

clear
if [ -f ../code/main.cpp ]; then
    g++ -std=c++20 -fsanitize=address -o ../exec/main.e ../code/main.cpp
    echo "COMPILED"
elif [ -f ../code/main.py ]; then
    rm ../exec/main.e
    touch ../exec/main.e
    chmod +x ../exec/main.e
    echo "python3 ../code/main.py" > ../exec/main.e
    echo "COMPILED (python)"
else
    echo "main COMPILE FAILED"
fi

all_passed=true
any_test=false
for test in ../test_o/*; do
    if [[ -d "$test" && $(basename "$test") =~ ^[0-9]+$ ]]; then
        test_num=$(basename "$test")
        in="$test/in"
        out="$test/out"
        ans="$test/ans"
        if [[ ! -f "$in" ]]; then
            echo "Test $test_num: Missing input file ($in), skipping."
            echo ""
            continue
        fi
        any_test=true
        ../exec/main.e < "$in" &> "$out"
        echo "Test $test_num: EXECUTED"
        if [[ -s "$ans" ]]; then
            if ! ./.comp "$out" "$ans"; then
                echo "Test $test_num: FAILED"
                all_passed=false
            else
                echo "Test $test_num: PASSED"
            fi
        else
            echo "Test $test_num: No answer file specified."
        fi
        echo ""
    fi
done

if $any_test; then
    if $all_passed; then
        echo "All tests PASSED!"
    else
        echo "Some tests FAILED."
    fi
else
    echo "No tests found."
fi